### ISSUE TITLE
Build tree suggestion.

### ISSUE THREAD

**Issue by mikobuntu** [sjaehn/bmusic-bslicer#1]
Hi @sjaehn , I noticed after running make that new files are created in the root of the build tree, i.e BSlicer.lv2/ BSlicer.so BSlicer_GUI.so , they are owned by ROOT as we have run the sudo command for building.
perhaps it would be better to either remove them right after the make install or have a separate build folder to work in ?

**Comment by sjaehn** [comment]
Thank you, you're right. BSlicer.so BSlicer_GUI.so will now go directly into the build folder (BSlicer.lv2) and will be deleted by (sudo) make clean.
